se agrego el primer archivo, zen de python
CrawKatt/kanizawa_sensei_bot pull request #57
Opened 2023-10-20 22:12 UTC by JuanPerdomo00

Estan pendientes el resto de archivos, mando este como ejemplar para los siguientes ficheros.

2023-10-20 22:16 UTC, CrawKatt requested changes
Se ve bien, pero lo ideal es que sea en Español. Por ejemplo, todos los ejemplos de código en Rust mantienen código en Inglés pero los Strings se mantienen en Español. Además los ejemplos deben ser ejemplos de conceptos sobre el código en Python. ¿que significa Zen? ¿que es lo que hace? ¿para que se usa?

2023-10-20 22:18 UTC, JuanPerdomo00 commented
ok, entonces las ree escribire en español.

2023-10-20 22:27 UTC, CrawKatt commented
una pregunta respecto a zen, es algún ejemplo de código en Python? lo ideal es que los docs de cada lang sean sobre los conceptos básicos y el como se usan ciertas keywords. Por ejemplo: ¿cómo se hacen variables en Python? ¿Qué son los diccionarios? ¿Qué son las clases?

2023-10-20 22:31 UTC, JuanPerdomo00 commented
Claro, yo tengo en cuenta eso que tu dices, pero imagino que van desde conceptos básicos hasta avanzados. El zen de python es por donde se empieza ya que es como se debe programar con python. Ya después de él empieza la explicación de python variables funciones ETC…

2023-10-20 22:32 UTC, CrawKatt commented
entiendo, ¿vas a subir otros ejemplos más o hago el merge?

2023-10-20 22:34 UTC, JuanPerdomo00 commented
Voy a subir unos cuantos más.

2023-10-20 22:36 UTC, CrawKatt commented
vale, dejo la PR abierta entonces para que vayas subiendo los demás a esta misma PR y un consejo, no es buena práctica hacer una PR desde tu rama main del Fork, el flujo ideal a seguir es crear una branch nueva con la característica que vas a añadir y luego hacer la PR desde esa branch

2023-10-21 00:58 UTC, JuanPerdomo00 commented
Por ahora son esos, para mañana se espera terminar unos cuantos mas.

2023-10-21 01:06 UTC, CrawKatt reviewed
Considera no usar nombres largos en los archivos.md. El Bot obtiene el texto de los archivos.md proporcionando el nombre de dicho archivo como argumento del comando.
Ejemplo:
`/python variables`
`/python operadores`

2023-10-21 01:08 UTC, JuanPerdomo00 commented
Corrigiendo de una

2023-10-21 13:16 UTC, CrawKatt reviewed
- El Archivo `Tobjetos.md` dejemoslo como `objetos.md`
- El archivo `tipos.md` queda mejor como `tipos_de_datos.md` con el fin de ser más semántico a la hora de usar el comando

2023-10-21 13:27 UTC, JuanPerdomo00 commented
Ok, pero el archivo  `tipos_de_datos.md` no era emaciado largo para el bot? Entonces como se haria ahi?

2023-10-21 13:31 UTC, CrawKatt commented
> Ok, pero el archivo `tipos_de_datos.md` no era emaciado largo para el bot? Entonces como se haria ahi?

no será demasiado largo. El comando en ese caso sería `/tipos_de_datos` considero que es más semántico así y no quedará tan largo

2023-10-21 13:34 UTC, JuanPerdomo00 commented
> > Ok, pero el archivo `tipos_de_datos.md` no era emaciado largo para el bot? Entonces como se haria ahi?
> 
> no será demasiado largo. El comando en ese caso sería `/tipos_de_datos` considero que es más semántico así y no quedará tan largo

ya quedaron cambiados y los ficheros anterios fuero borrados

2023-10-21 13:36 UTC, CrawKatt commented
> > > Ok, pero el archivo `tipos_de_datos.md` no era emaciado largo para el bot? Entonces como se haria ahi?
> > 
> > 
> > no será demasiado largo. El comando en ese caso sería `/tipos_de_datos` considero que es más semántico así y no quedará tan largo
> 
> ya quedaron cambiados y los ficheros anterios fuero borrados

hago el merge o subirás más archivos?

2023-10-21 13:46 UTC, JuanPerdomo00 commented
> hago el merge o subirás más archivos?
haz el merge, en la tarde subire otro pull

2023-10-21 13:47 UTC, CrawKatt commented
vale, muchas gracias por la ayuda y la contribución

2023-10-21 13:47 UTC, merged